name: CI Build

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    env:
      QT_VERSION: 6.5.3
      QT_INSTALL_DIR: D:/a/Notepad--/Qt
      BUILD_DIR: D:/a/Notepad--/Notepad--/build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt
        shell: pwsh
        run: |
          $qtInstallerUrl = "https://download.qt.io/official_releases/online_installers/qt-unified-windows-x64-online.exe"
          $installerPath = "$env:TEMP\qt-unified-windows-x64-online.exe"
          Invoke-WebRequest -Uri $qtInstallerUrl -OutFile $installerPath -TimeoutSec 1200
          # Run Qt installer
          Start-Process -FilePath $installerPath -ArgumentList `
            'install', '--no-default-installations', '--accept-licenses', `
            '--no-force-installations', '--confirm-command', `
            '-p', "qt.qt${{ env.QT_VERSION }}.win64_msvc2019_64", `
            '--root', "${{ env.QT_INSTALL_DIR }}" `
            -NoNewWindow -Wait
          # Verify Qt installation
          if (-Not (Test-Path "${{ env.QT_INSTALL_DIR }}\${{ env.QT_VERSION }}")) {
            throw "Qt installation failed!"
          } else {
            Write-Host "Qt installation verified"
          }

      - name: Configure CMake
        shell: pwsh
        run: |
          cmake -B "${{ env.BUILD_DIR }}" `
            -DCMAKE_CXX_COMPILER=cl `
            -DCMAKE_C_COMPILER=cl `
            -DCMAKE_BUILD_TYPE=Release `
            -G "Ninja" `
            -S "${{ github.workspace }}"
        env:
          Qt6_DIR: ${{ env.QT_INSTALL_DIR }}/6.5.3/msvc2019_64
          QT_PLUGIN_PATH: ${{ env.QT_INSTALL_DIR }}/6.5.3/msvc2019_64/plugins
          QML2_IMPORT_PATH: ${{ env.QT_INSTALL_DIR }}/6.5.3/msvc2019_64/qml

      - name: Build project
        shell: pwsh
        run: cmake --build "${{ env.BUILD_DIR }}" --config Release

      - name: Run tests
        working-directory: "${{ env.BUILD_DIR }}"
        shell: pwsh
        run: ctest --output-on-failure --build-config Release
