name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v4

    # Install dependencies for Ubuntu (Qt6)
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build
        sudo add-apt-repository ppa:beineri/opt-qt-6.5.2-jammy -y
        sudo apt-get update
        sudo apt-get install -y qt6-base-dev qt6-base-dev-tools
        echo "CMAKE_PREFIX_PATH=/opt/qt6.5.2/lib/cmake" >> $GITHUB_ENV

    # Install dependencies for macOS
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install ninja qt
        echo "CMAKE_PREFIX_PATH=$(brew --prefix qt)" >> $GITHUB_ENV

    # Set up MSVC on Windows
    - name: Set up MSVC (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/setup-msbuild@v1

    # Set up Visual Studio environment for CMake on Windows
    - name: Set up Visual Studio (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        vswhere -products * -latest -property installationPath
        $vsPath = vswhere -products * -latest -property installationPath
        echo "VS path: $vsPath"
        echo "CMAKE_PREFIX_PATH=$vsPath" >> $GITHUB_ENV

    # Configure CMake
    - name: Configure CMake
      run: |
        cmake -B ${{ steps.strings.outputs.build-output-dir }} \
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
        -DCMAKE_BUILD_TYPE=Release \
        -G "Ninja" \
        -S ${{ github.workspace }}
      shell: |
        if: matrix.os == 'windows-latest'
          pwsh
        else
          bash

    # Build the project
    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release

    # Run tests
    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      env:
        DISPLAY: ':0' # Necessary for GUI tests on Ubuntu
      run: ctest --output-on-failure --build-config Release
