name: Build and Release

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_extension: tar.gz
          - os: macos-latest
            artifact_extension: zip
          - os: windows-latest
            artifact_extension: zip

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Windows Section
    - name: Check Visual Studio Build Tools Path
      if: matrix.os == 'windows-latest'
      run: |
        echo "Checking for Visual Studio Build Tools..."
        dir "C:\Program Files (x86)\Microsoft Visual Studio" /b
        dir "C:\Program Files\Microsoft Visual Studio" /b
        if not exist "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat" (
          echo "Visual Studio Build Tools not found in default path."
          exit 1
        )

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install qt --version=6.5.3 -y
        choco install ninja -y
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        choco install visualstudio2022buildtools -y --install-arguments \
          '--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --quiet --norestart'

    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat" && ^
        cmake -B D:\a\Notepad--\Notepad--\build ^
          -DCMAKE_BUILD_TYPE=Release ^
          -DCMAKE_PREFIX_PATH="C:\Qt\6.5.3\msvc2019_64\lib\cmake" ^
          -G Ninja ^
          -S D:\a\Notepad--\Notepad--
      shell: cmd

    - name: Build application (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat" && ^
        cmake --build D:\a\Notepad--\Notepad--\build --config Release
      shell: cmd

    - name: Package application (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd D:\a\Notepad--\Notepad--\build
        Compress-Archive -Path . -DestinationPath application.zip
      shell: cmd

    # Upload Artifacts
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: application-${{ matrix.os }}
        path: |
          D:\a\Notepad--\Notepad--\build\application.${{ matrix.artifact_extension }}
