name: Build and Release

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_extension: tar.gz
          - os: macos-latest
            artifact_extension: zip
          - os: windows-latest
            artifact_extension: zip

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Install dependencies
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build \
            qt6-base-dev qt6-tools-dev qt6-tools-dev-tools \
            qt6-l10n-tools libgl1-mesa-dev libglu1-mesa-dev rsync

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install ninja qt

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install qt --version=6.5.3 -y
        choco install ninja -y
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

    # Debug and verify environment for Windows
    - name: Debug environment paths (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        echo "Checking Visual Studio paths..."
        if exist "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat" (
          echo "Found vcvars64.bat"
        ) else (
          echo "vcvars64.bat not found"
          exit 1
        )
      shell: cmd

    # Configure CMake
    - name: Configure CMake (Ubuntu and macOS)
      if: matrix.os != 'windows-latest'
      run: |
        cmake -B "${{ github.workspace }}/build" \
          -DCMAKE_BUILD_TYPE=Release \
          -G "Ninja" \
          -S "${{ github.workspace }}"
      shell: bash

    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat" && ^
        cmake -B D:\a\Notepad--\Notepad--\build ^
          -DCMAKE_BUILD_TYPE=Release ^
          -DCMAKE_PREFIX_PATH="C:\Qt\6.5.3\msvc2019_64\lib\cmake" ^
          -G Ninja ^
          -S D:\a\Notepad--\Notepad-- 
      shell: cmd

    # Build Application
    - name: Build application (Ubuntu and macOS)
      if: matrix.os != 'windows-latest'
      run: cmake --build "${{ github.workspace }}/build" --config Release
      shell: bash

    - name: Build application (Windows)
      if: matrix.os == 'windows-latest'
      run: cmake --build "D:\a\Notepad--\Notepad--\build" --config Release
      shell: cmd

    # Package Application
    - name: Package application (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        BUILD_DIR="${{ github.workspace }}/build"
        TEMP_DIR="/tmp/build_copy"
        rm -rf $TEMP_DIR
        rsync -a "$BUILD_DIR/" "$TEMP_DIR/"
        cd $TEMP_DIR
        tar -czvf application.tar.gz ./*
        mv application.tar.gz $BUILD_DIR/

    - name: Package application (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        cd "${{ github.workspace }}/build"
        hdiutil create -volname Application -srcfolder . -ov -format UDZO application.dmg
        zip application.zip application.dmg

    - name: Package application (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd "D:\a\Notepad--\Notepad--\build"
        Compress-Archive -Path . -DestinationPath application.zip
      shell: pwsh

    # Upload Artifacts
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: application-${{ matrix.os }}
        path: |
          ${{ github.workspace }}/build/application.${{ matrix.artifact_extension }}
