name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v4

    # Install dependencies for Ubuntu (Qt6 + OpenGL)
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build qt6-base-dev qt6-base-dev-tools libgl-dev libgl1-mesa-dev
        echo "CMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt6" >> $GITHUB_ENV

    # Install dependencies for macOS
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install ninja qt
        echo "CMAKE_PREFIX_PATH=$(brew --prefix qt)" >> $GITHUB_ENV

    # Install Visual Studio Build Tools (Windows)
    - name: Install Visual Studio Build Tools (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install visualstudio2019buildtools -y
        choco install ninja -y
        vswhere -products * -latest -property installationPath | Out-File -FilePath vs-path.txt
        $vs_path = Get-Content vs-path.txt
        echo "$vs_path\MSBuild\Current\Bin" >> $GITHUB_ENV
        echo "CMAKE_CXX_COMPILER=cl" >> $GITHUB_ENV
        echo "CMAKE_C_COMPILER=cl" >> $GITHUB_ENV

    # Configure CMake (Linux and macOS)
    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build \
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
        -DCMAKE_BUILD_TYPE=Release \
        -G "Ninja" \
        -S ${{ github.workspace }}

    # Build the project
    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config Release

    # Run tests
    - name: Test
      working-directory: ${{ github.workspace }}/build
      env:
        DISPLAY: ':0' # Necessary for GUI tests on Ubuntu
      run: ctest --output-on-failure --build-config Release
